services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    mem_limit: 10g        # Limita el uso a 10 GB (protege al sistema)
    mem_reservation: 6g   # Sugerencia mínima para que no se “ahogue”    
    env_file:
      - .env
    networks:
      - ai_shared_services

    # Si querés usar GPU, agregá:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  ollama_data:

networks:
  ai_shared_services:
    external: true